### ISSUE TITLE
Script error in MethGeno.pm

### ISSUE THREAD

**Issue by chenzixi07** [xie186/ViewBS#12]
I found the script MethGeno could not run with testdata. I am new to perl, but after checking I found the code in MethGeno.pm line 38~44 could be wrong:
if(-e $opts_sub->{genomeLength}){
	    print "Error: $opts_sub->{genomeLength} not exists!\n";
	    print "Please provide correct --genomeLength!\n";
	    #+$exit_code; 
	    exit 0;
       }
        $opts_sub->{genomeLength} = abs_path $opts_sub->{genomeLength};

I think it should be
if(-e $opts_sub->{genomeLength}){
	   $opts_sub->{genomeLength} = abs_path $opts_sub->{genomeLength};
        }

It works after this change.

**Comment by xie186** [comment]
@chenzixi07 Thanks for reporting this bug. 

https://github.com/xie186/ViewBS/commit/f1f2f8d234160a94f9f2b71a5b3dfd3928c7f4b6

Please let me know if there are other bugs. Thanks again.
