### ISSUE TITLE
关于在运行ViewBS MethCoverage时候报错

### ISSUE THREAD

**Issue by qliugithub** [xie186/ViewBS#13]
**我在testdata目录下运行manual中的命令如下：**
../../ViewBS MethCoverage --reference TAIR10_chr_all.fasta --sample bis_WT.tab.gz,WT --sample bis_cmt23.tab.gz,cmt23 --sample bis_cmt2-3.tab.gz,cmt2-3 --sample bis_drm12cmt23.tab.gz,drm12cmt12 --sample bis_drm12cmt2.tab.gz,drm12cmt2 --outdir methCoverage --prefix cmt2_proj_allsam
**但是程序报错了**
Subcommand: MethCoverage
Please provide --sample!
Sample(s): 
Please provide --reference!
ARRAY(0x9e4a70) ne BisNonConvRate
**但是我使用sh test_ViewBS.sh 运行时候没有报错，请问一下改如何解决呢？困扰了一天了。**
谢谢了！

**Comment by xie186** [comment]
Are you using the latest version (https://github.com/xie186/ViewBS/releases/tag/ViewBS_v0.1.3)? If not, please use the latest version. 
I tried your command line and didn't get the error message you got. 
If you are using the latest version, could you please give a screenshot of your command line?

**Comment by qliugithub** [comment]
Thanks ! I had solved . I was used ViewBS instead of ../../ViewBS, and then can run , It's just so magic. but I didn't find why use ../../ViewBS can't run.
I find some mistake in running MethLevDist , It's should be ViewBS rather than ViewBS,pl. just a a slip of a pen.
Finally I  offered my appreciation to your answer and forgive my poor English.

**Comment by xie186** [comment]
Glad you already solved this problem. Please let us know if you have any problem in the future. 
Best,
Shaojun

**Comment by ryys1122** [comment]
In some version of perl or Getopt::Long::Subcommand, the following code does't work correctly
'sample:s'               => \@{$opts_subcmd{sample}},
the following one  works well
'sample=s'               => \@{$opts_subcmd{sample}},

**Comment by xie186** [comment]
@ryys1122 could you please let me know the version you tried? Thanks for reporting this.

**Comment by ryys1122** [comment]
Getopt::Long::Subcommand  0.102, Perl 5.22.1
Getopt::Long::Subcommand 0.102, Perl 5.26.1

**Comment by xie186** [comment]
Got it. Thanks. We'll test this shortly.

**Comment by AbRawoof** [comment]
Hello every one,
u@u:~/Downloads/ViewBS-ViewBS_v0.1.3$perl ViewBS MethCoverage --reference GCF_0007108_genomic.fasta --sample S1_cov10x_CX_report.txt.gz,S1 --sample S2_cov10x_CX_report.txt.gz,S2 --sample S3_cov10x_CX_report.txt.gz,S3 --sample S4_cov10x_CX_report.txt.gz,S4 --outdir myCoverage

Error Message:
Subcommand: MethCoverage
Please provide --sample!
Sample(s): 
Please provide --reference!
ARRAY(0x559bf30de220) ne BisNonConvRate

#############
My files are bismark methylation extraction output files and I have followed bgzip for zipping file and tabix for indexcing. 
Please let me where I am going wrong.
Thanks

**Comment by xie186** [comment]
Could you please tell the which version you're using?

**Comment by AbRawoof** [comment]
I m using ViewBS_v0.1.3

**Comment by AbRawoof** [comment]
I am using perl-5.24.1,  Bio-DB-HTS-2.9 and Getopt-Long-Subcommand-0.102 and  ViewBS-v0.1.3 version.
I am puzzled about the message given as it is not taking input for samples as well as reference.

**Comment by AbRawoof** [comment]
Hello.. 
Please help me out. Where I am going wrong. I have done proper installation and have all packages as mentioned in your installation guide.
Do I need to make some changes in any script..
Thanks,

**Comment by xie186** [comment]
​Sorry for the late response. I was out of town. I’ll help you out today.

________________________________

**Comment by xie186** [comment]
Hi @AbRawoof,
I didn't see anything wrong with the command line. Is it possible you can provide me the files you are using? I couldn't get the same error you got. Thanks.

**Comment by AbRawoof** [comment]
Hi @xie186 .
I have tried in other system having same configuration but ubuntu version is different 17.10 instead of 17.02.
The program is working fine in that system.

I think I might have missed some library. Will work on that.

Thanks.

**Comment by xie186** [comment]
I tested ViewBS in Ubuntu 16.04. It works fine, 

Is it possible that I can get access to 17.02 of yours to see whether I can fix this if it's a bug?  Thanks.

**Comment by AbRawoof** [comment]
Hello @xie186 ..
Sorry for late response..I have installed kubuntu 17.10 and now the problem is sorted out. Thanks for  your response.

Best,
Abdul
