### ISSUE TITLE
How to solve the MethOverRegion error？

### ISSUE THREAD

**Issue by wangzer** [xie186/ViewBS#14]
Thank you very much for the tools you developed, great! However, I encountered a small problem when in use, trouble you help solve it. When I use the MethOverRegion function, I get the following error:

wangze@jinglab:~/bioinf/dh/ler-cvi_wgbs-wgs/wgbs/viewBS$ ViewBS MethOverRegion --region TAIR10_GFF3_genes_chr1.bed --sample cvi_pe_rep.bismark.cov.gz,Cvi --sample ler_pe_rep.bismark.cov.gz,Ler --prefix cvi_ler-bis_TE_chr1_sample --context CG

Subcommand: MethOverRegion
cvi_pe_rep.bismark.cov.gz,Cvi ler_pe_rep.bismark.cov.gz,Ler
TAIR10_GFF3_genes_chr1.bed

It seemed that the reigons you provided are Genes. Please make sure of this.

Output directory is: /home/wangze/bioinf/dh/ler-cvi_wgbs-wgs/wgbs/viewBS
Output prefix: cvi_ler-bis_TE_chr1_sample
Start calculate methylation information for target context
CG
.........
.........
Warning message:
In min(tab$bin_num) : no non-missing arguments to min; returning Inf
Warning message:
In max(tab$bin_num) : no non-missing arguments to max; returning -Inf
Meth::OverRegion=HASH(0x12a5d88): Usage: R --vanilla --slave --height <fig height> --width <fig width> --adjustXaxis <X> --input <input tab> --xlab <Gene>  --output <output> < OverRegion.R 
/usr/local/lib/R/bin/exec/R --slave --no-restore --file=/home/wangze/biosoft/ViewBS/lib/Meth/OverRegion.R --args --input /home/wangze/bioinf/dh/ler-cvi_wgbs-wgs/wgbs/viewBS/cvi_ler-bis_TE_chr1_sample_MethOverRegion_CG.txt --xlab Gene --height 10 --width 10 --adjustXaxis 10 --output /home/wangze/bioinf/dh/ler-cvi_wgbs-wgs/wgbs/viewBS/cvi_ler-bis_TE_chr1_sample_MethOverRegion_CG.pdf 

Running time: 1 wallclock secs ( 0.55 usr  0.02 sys +  0.63 cusr  0.07 csys =  1.27 CPU)

  wangze
[cvi_ler-bis_TE_chr1_sample_MethOverRegion_CG.pdf](https://github.com/xie186/ViewBS/files/1611576/cvi_ler-bis_TE_chr1_sample_MethOverRegion_CG.pdf)

**Comment by xie186** [comment]
Could you send me the file with the name of "cvi_ler-bis_TE_chr1_sample_MethOverRegion_CG.txt"?

**Comment by wangzer** [comment]
[cvi_ler-bis_TE_chr1_sample_MethOverRegion_CG.txt](https://github.com/xie186/ViewBS/files/1615406/cvi_ler-bis_TE_chr1_sample_MethOverRegion_CG.txt)
This is my txt file.

**Comment by xie186** [comment]
It seems that the result file is empty. Could you check the input file `TAIR10_GFF3_genes_chr1.bed`, `cvi_pe_rep.bismark.cov.gz` and `ler_pe_rep.bismark.cov.gz`? If possible, could you please show me the head 10 lines of these three files? Thanks.

**Comment by wangzer** [comment]
This is part of my three documents：
![tair10_gff3_genes_chr1 bed](https://user-images.githubusercontent.com/20257218/34751568-7650a878-f5e8-11e7-9a08-640177768707.png)
![cvi_pe_rep bismark cov gz](https://user-images.githubusercontent.com/20257218/34751569-76896a5a-f5e8-11e7-93b8-356d4ef62f2f.png)
![ler_pe_rep bismark cov gz](https://user-images.githubusercontent.com/20257218/34751570-76bc4268-f5e8-11e7-967d-d625b62fc426.png)

**Comment by xie186** [comment]
Sorry for the late response. I think the problem is that the format of chromosome IDs in the first file is not consistent with the ones you are using in the second and third file. What you can do is to remove "chr" in the first file. Please let me know if you have further questions. Good luck.

**Comment by wangzer** [comment]
After I delete chr, the program is running successfully

**Comment by anupambh** [comment]
Hi,
I am trying to run MethOverRegion command and ViewBS gave the error. I am working on GRCh38. I have generated the files by using Bismark Genome-wide Cytosine Methylation Report followed by gzip and tabix indexing as mentioned in the ViewBS manual.

command:
/opt/viewBS-conda/ViewBS-0.1.7/ViewBS MethOverRegion --region 117.lncrna.MT.sorted.bed --sample ENCFF000MEU_trimmed_bismark_bt2.bismark.cytosine.cov.CX_report.txt.gz,ENCFF000MEU --prefix ENCFF000MEU --context CG --outdir MethOverRegion

Error:

Subcommand: MethOverRegion
ENCFF000MEU_trimmed_bismark_bt2.bismark.cytosine.cov.CX_report.txt.gz ENCFF000MEU_trimmed_bismark_bt2.bismark.cytosine.cov.CX_report.txt.gz,ENCFF000MEU
117.lncrna.MT.sorted.bed

It seemed that the reigons you provided are Genes. Please make sure of this.

Output directory is: /home/bif/methylation/ENCSR000DDK/MethOverRegion
Output prefix: ENCFF000MEU
Use of uninitialized value $sam_name in concatenation (.) or string at /opt/viewBS-conda/ViewBS-0.1.7/lib/Meth/Sample.pm line 83.
Start calculate methylation information for target context
CG


CG


Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 1 did not have 6 elements
Calls: read.table -> scan
Execution halted
Meth::OverRegion=HASH(0x24f1f60): Usage: R --vanilla --slave --height <fig height> --width <fig width> --adjustXaxis <X> --input <input tab> --xlab <Gene>  --output <output> < OverRegion.R
/home/bif/miniconda2/envs/env_ViewBS/lib/R/bin/exec/R --slave --no-restore --file=/opt/viewBS-conda/ViewBS-0.1.7/lib/Meth/OverRegion.R --args --input /home/bif/methylation/ENCSR000DDK/MethOverRegion/ENCFF000MEU_MethOverRegion_CG.txt --xlab Gene --height 10 --width 10 --adjustXaxis 10 --output /home/bif/methylation/ENCSR000DDK/MethOverRegion/ENCFF000MEU_MethOverRegion_CG.pdf

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 1 did not have 6 elements
Calls: read.table -> scan
Execution halted
Meth::OverRegion=HASH(0x24f1f60): Usage: R --vanilla --slave --height <fig height> --width <fig width> --adjustXaxis <X> --input <input tab> --xlab <Gene>  --output <output> < OverRegion.R
/home/bif/miniconda2/envs/env_ViewBS/lib/R/bin/exec/R --slave --no-restore --file=/opt/viewBS-conda/ViewBS-0.1.7/lib/Meth/OverRegion.R --args --input /home/bif/methylation/ENCSR000DDK/MethOverRegion/ENCFF000MEU_MethOverRegion_CG.txt --xlab Gene --height 10 --width 10 --adjustXaxis 10 --output /home/bif/methylation/ENCSR000DDK/MethOverRegion/ENCFF000MEU_MethOverRegion_CG.pdf

Running time: 7 wallclock secs ( 3.59 usr  0.01 sys +  0.75 cusr  0.07 csys =  4.42 CPU)

117.lncrna.MT.sorted.bed file:

1       105956716       106042738       RP5-947P14.1    +       MTlincrna
1       72765031        72791282        RP11-262K1.1    +       MTlincrna
1       41375004        41375669        RP11-399E6.4    +       MTlincrna
1       155978799       155982986       RP11-336K24.12  +       MTlincrna
2       74832655        74833987        RP11-259N19.1   +       MTlincrna
2       104434378       104512757       LINC01102       +       MTlincrna
3       177010719       177011067       MTND5P15        +       MTlincrna
3       177010719       177011067       MTND5P15        +       MTlincrna
4       37588087        37588875        RP11-36B15.1    +       MTlincrna
4       27262506        27267254        RP11-415C15.3   +       MTlincrna

ENCFF000MEU_trimmed_bismark_bt2.bismark.cytosine.cov.CX_report.txt.gz file:

2       10001   +       0       0       CG      CGT
2       10002   -       0       0       CG      CGN
2       10006   +       0       0       CHH     CCC
2       10007   +       0       0       CHH     CCA
2       10008   +       0       0       CHH     CAC
2       10010   +       0       0       CHH     CAC
2       10012   +       0       0       CHH     CAC
2       10014   +       0       0       CHH     CCA
2       10015   +       0       0       CHH     CAC
2       10017   +       0       0       CHH     CAC
2       10019   +       0       0       CHH     CCC
2       10020   +       0       0       CHH     CCA
2       10021   +       0       0       CHH     CAC
2       10023   +       0       0       CHH     CAC

The generated ENCFF000MEU_MethOverRegion_CG.txt file contains only 5 columns:

sample_name     region  bin_num C_number        T_number        Methylation_level
        Body    1       100     2847    0.0339328130302002
        Body    11      34      1064    0.0309653916211293
        Body    15      0       16      0
        Body    16      44      62      0.415094339622642
        Body    2       10      773     0.0127713920817369
        Body    21      78      431     0.153241650294695
        Body    22      2       58      0.0333333333333333
        Body    23      1       27      0.0357142857142857
        Body    24      2       25      0.0740740740740741



Any help would be appreciated.


Regards;
Anupam
