### ISSUE TITLE
problem about "OverRegion.pm"

### ISSUE THREAD

**Issue by ChengYunazhi** [xie186/ViewBS#16]
Hi, 

 first of all,  ViewBS is a nice work, thanks for sharing this packages. I cloned today and run the example command, error was reported as below:
<img width="1110" alt="qq20180331-224021 2x" src="https://user-images.githubusercontent.com/13846735/38164339-66366522-3535-11e8-900c-3d31198fdeac.png">

all testdata was download from gitlab and with no modification, how did this error happened, it seems like a format problem in region file? 

Thanks

Yuanzhi

**Comment by xie186** [comment]
Hi Yuanzhi, Could you please tell me which version you're using? Could you try the latest version (https://github.com/xie186/ViewBS/releases/tag/ViewBS_v0.1.4)?  Thanks for using ViewBS.

**Comment by ChengYunazhi** [comment]
Hi Shaojun, I download and installed latest version of ViewBS (0.1.4), and error was still there: 
<img width="1227" alt="qq20180401-105243 2x" src="https://user-images.githubusercontent.com/13846735/38169385-64a44eca-359b-11e8-97e5-82fee7aa16ff.png">
as you can see, overregion.pm in lib of viewBS 0.1.4 was used. 

Thanks!

**Comment by xie186** [comment]
Could you please check it again? Sorry for the inconvenience. https://github.com/xie186/ViewBS/releases/tag/ViewBS_v0.1.4

**Comment by ChengYunazhi** [comment]
this time those command work well, and output expected results. 

<img width="1199" alt="22" src="https://user-images.githubusercontent.com/13846735/38169610-4f022410-35a1-11e8-9b7a-68a726779930.png">

Thanks, Shaojun !

**Comment by xie186** [comment]
Great! Please let me know if you have any questions or any suggestions. Thanks.

**Comment by ChengYunazhi** [comment]
Hi, Shaojun, another suggestion: png and pdf files could be printed out at the same time, png can be used in rmarkdown rendered html file, if users want to report some of WGBS results, which visulized by ViewBS. 

Thanks

**Comment by xie186** [comment]
Thanks for your suggestion. I'll add this feature later.
