### ISSUE TITLE
MethHeatmap error

### ISSUE THREAD

**Issue by ChengYunazhi** [xie186/ViewBS#18]
Hi @xie186 ,

    error was reported by ViewBS MethHeatmap subcommand: 

![qq 20180511144020](https://user-images.githubusercontent.com/13846735/39910344-7114c826-5529-11e8-97cc-9a713bca3d79.png)

--------------------

Whether to consider the gene encoding strand when calculating the average methylation level of a given gene?  

If gene coding in minus strand, and in this region all methylated C are in plus strand, methylation level for this gene is 0 or >0 ?

Thanks!

 Yuanzhi

**Comment by xie186** [comment]
Sorry for the late response. Do you still have the problem? I can sort it out on the weekend.

**Comment by xie186** [comment]
For heatmap it doesn't take the strand information into consideration.
