### ISSUE TITLE
add metagene option in meth over region

### ISSUE THREAD

**Issue by xiuru** [xie186/ViewBS#20]
Hello Shaojun,
Thank you for developing such a useful tools. And it is very convenient to use.
I am wondering is it possible to add a option just like '--metagene' ?
And the explanation of '--metagene' in deeptools is:
When either a BED12 or GTF file are used to provide regions, perform the computation on the merged exons, rather than using the genomic interval defined by the 5-prime and 3-prime most transcript bound (i.e., columns 2 and 3 of a BED file). If a BED3 or BED6 file is used as input, then columns 2 and 3 are used as an exon.

So we can just plot the methylation level of exons or other interested regions.

Thank you,
Xiuru

**Comment by xie186** [comment]
Thank you for your suggestion. I’ll look into this later.
