### ISSUE TITLE
how to generate a file include the methyaltion level for each gene in a group

### ISSUE THREAD

**Issue by xiuru** [xie186/ViewBS#21]
Hello Shaojun,
I want to study the differences of DNA methylation patterns of 2 groups genes and got the figure successfully. The prefix_MethOverRegion_CG.txt file only include the average methylation levels of each group . Like this:
sample_name	region	bin_num	C_number	T_number	Methylation_level
a	Body	1	11748	108941	0.0973410998516849
a	Body	10	34600	55444	0.384256585669228
b	Body	1	22093	293248	0.0700606644870156
b	Body	10	83754	139327	0.375442103989134
 I am wondering how can i generate a file that include all the methylation levels of each gene in my interested group.

Thank you in advance.Looking forward to your reply.
Xiuru

**Comment by xie186** [comment]
Hi Xiuru,
I assume you want to get the methylation levels for each gene or a specific region across multiple samples. If so, you can try subcommand `MethHeatmap`. Please let me know whether this helps.
Best,
Shaojun

**Comment by xiuru** [comment]
Hi Shaojun,
Thanks for your help. I tried MethHeatmap and got the methylation values for each gene.

Best,
Xiuru
