### ISSUE TITLE
algorithm under viewBS??

### ISSUE THREAD

**Issue by ChengYunazhi** [xie186/ViewBS#23]
Hi @xie186 ，

     which algorithm is used in viewBS when calculating region methylation level? 

   
![1](https://user-images.githubusercontent.com/13846735/47995009-faf67080-e12e-11e8-806f-d84dfc597f7b.png)
![2](https://user-images.githubusercontent.com/13846735/47995012-fdf16100-e12e-11e8-9e51-8a59c371790f.png)

**Comment by xie186** [comment]
Thanks for using ViewBS. By default, ViewBS use `weighted methylation level`. 
But for `GlobalMethLev` and `MethLevDist`, there is an option of `--methodAverage` which will use `mean methylation level`. 
We just released a new version of `ViewBS`: https://github.com/xie186/ViewBS/releases/tag/v0.1.5. Please use the latest version. Let us know if you have any other questions.
