### ISSUE TITLE
Problem to run test data

### ISSUE THREAD

**Issue by davidries84** [xie186/ViewBS#25]
Hi,
I cloned https://gitlab.com/BS-seq/ViewBS_testdata im my ViewBS folder.
But when running
`sh test_ViewBS.sh `
I get 
...

> Subcommand: BisNonConvRate
> Sample list: 
> Please provide --sample!
> 
> Error: Please provide --chrom for the chromosome IDs that you want to use to estimate the non-conversion rate!

Maybe you could fix the script for your test data?

Best,

David

**Comment by xie186** [comment]
Hi David, 

Could you please share me with your configuration? E.g. Perl version, the command line of `BisNonConvRate` in `test_ViewBS.sh`. 
I'm fine running the command line.  

Best,
Shaojun

**Comment by davidries84** [comment]
Hi Shaojun,

> perl --version
> This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

` ./memusg perl $Path2ViewBS/ViewBS BisNonConvRate --sample bis_WT.tab.gz,WT --sample bis_cmt23.tab.gz,cmt23 --sample bis_cmt2-3.tab.gz,cmt2-3 --sample bis_drm12cmt23.tab.gz,drm12cmt23 --sample bis_drm12cmt2.tab.gz,drm12cmt2 --outdir BisNonConvRate --prefix cmt2_proj_allsam --chr chrC --height 10 --width 14`

If I run it like this from the command line, it runs:

` perl ../../ViewBS BisNonConvRate --sample bis_WT.tab.gz,WT --sample bis_cmt23.tab.gz,cmt23 --sample bis_cmt2-3.tab.gz,cmt2-3 --sample bis_drm12cmt23.tab.gz,drm12cmt23 --sample bis_drm12cmt2.tab.gz,drm12cmt2 --outdir BisNonConvRate --prefix cmt2_proj_allsam --chr chrC --height 10 --width 14`

Best,
David

**Comment by lileiting** [comment]
Hi David, 

I also encountered this problem. I found that ViewBS was not working with perl-v5.26.1 (v5.26.2 in your case), but working with perl-v5.16.3 and perl-v5.18.2. I didn't figure out why, but you may try perl-v5.16 or perl-v.18. 

Best,
Leiting

**Comment by davidries84** [comment]
Hi Leiting,

thank you for the suggestion. Did you encounter any further problems using the wrong perl version?

Best,

David

**Comment by xie186** [comment]
Hi @davidries84,

Thanks for your information. I'll enable ViewBS to be able install using Conda during the holiday. That way you don't need to worry about the configuration. 
I'll let you know when it's ready. Currently I think the best way is to use the version @lileiting mentioned. 
 
Best,
Shaojun

**Comment by anupambh** [comment]
Hi,
I am trying to run the testdata and use the commands in your tutorial. But I got the following error:

Subcommand: MethCoverage
Please provide --sample!
Sample(s):
Please provide --reference!

command:

/opt/ViewBS-0.1.6/ViewBS MethCoverage --reference TAIR10_chr_all.fasta --sample bis_WT.tab.gz,WT --sample bis_cmt23.tab.gz,cmt2-3 --sample bis_cmt2-3.tab.gz,cmt2-3 --sample bis_drm12cmt23.tab.gz,drm12cmt12 --sample bis_drm12cmt2.tab.gz,drm12cmt2 --outdir methCoverage/ --prefix cmt2_proj_allsam

I am having the following perl version installed:

perl --version

This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-thread-multi
(with 79 registered patches, see perl -V for more detail)


Any suggestions would be very helpful for me.

Regards;
Anupam

**Comment by xie186** [comment]
Hi Anupam,
Thanks for using ViewBS. Could you please `ls` the folder you ran the command line?
Best,
Shaojun

**Comment by anupambh** [comment]
Hi,
Here is the content of the test folder.

bis_cmt2-3.tab
bis_cmt23.tab.gz
bis_cmt2-3.tab.gz.tbi
bis_cmt23.tab.gz.tbi
bis_drm12cmt23.tab.gz
bis_drm12cmt23.tab.gz.tbi
bis_drm12cmt2.tab.gz
bis_drm12cmt2.tab.gz.tbi
bis_WT.tab.gz
bis_WT.tab.gz.tbi
CHG_hypo_DMR_drm12cmt23_to_WT.txt
memusg
methCoverage
sampl_info_tab.txt
TAIR10_chr_all.fasta
TAIR10_chr_all.fasta.fai
TAIR10_GFF3_genes.bed
TAIR10_GFF3_genes_chr1.bed
TAIR10_GFF3_genes_prot.bed
TAIR10_GFF3_genes.WT.rank1.tab
TAIR10_GFF3_genes.WT.rank2.tab
TAIR10_GFF3_genes.WT.rank3.tab
TAIR10_GFF3_genes.WT.rank4.tab
TAIR10_GFF3_genes.WT.rank5.tab
TAIR10_Transposable_Elements.chr1.bed
TAIR10_Transposable_Elements.sim_xie.bed
test_ViewBS.sh

Regards;
Anupam

**Comment by xie186** [comment]
Thanks. I'll look into this and get back to you.

**Comment by xie186** [comment]
Hi Anupam,

Currently I'm still working on this. I already repeated the error you encountered. It may spend some time for debugging. But you can use other versions of Perl. 

The versions I have tested are:
perl-v5.14.4
perl-v5.16.3
perl-v5.18.2
perl-v5.22.1

The versions don't work:
v5.24.1
v5.26.*

I suggest you use `conda` to install `ViewBS`: https://github.com/xie186/ViewBS/wiki/Install-ViewBS-using-conda

Best,
Shaojun

**Comment by anupambh** [comment]
Hi,
I have installed ViewBS by using conda. Installation is successful and the testdata is working fine.

Thank you very much for the support.

Regards;
Anupam

**Comment by xie186** [comment]
As shown [here:](https://stackoverflow.com/questions/54888981/incorrect-behavior-of-perl-module-getoptlongsubcommand-in-perl-version-5-2), the problem is because:

> Getopt::Long::Subcommand relies on Getopt::Long, but it's incompatible with Getopt::Long 2.43 (inclusive) to 2.50 (exclusive).
> The simple solution is to upgrade to the latest version of Getopt::Long.

I tried upgrading Getopt::Long to version 2.50 by using `cpanm Getopt::Long` in perl-v5.24.1. As of 2/26/2019, version 2.5 was installed. Everything ran fine.
