### ISSUE TITLE
BisNonConvRate should return exit status != 0 upon failure

### ISSUE THREAD

**Issue by davidries84** [xie186/ViewBS#27]
Hi,

I ran BisNonConvRate (ViewBS Version 0.1.6.) and it failed, but apparently returned error status 0,
which made my workflow go on instead of exiting. Maybe this should be changed to something else?

Here is the output:

> Use of uninitialized value $sam_name in concatenation (.) or string at /biodata/irg/grp_stich/Hv-DRR-pop/bin/ViewBS_0.6.1/ViewBS-0.1.6/lib/Meth/Sample.pm line 36, <SAM> line 1.
Error: Faceting variables must have at least one value
Execution halted

I guess the error is, because some of my Chromosomes don't have methylation at all?

Best,
David

**Comment by xie186** [comment]
Hi David,
Thanks for reporting this to us. We already modified the code. Please let us know if you have any other suggestions. 

Here is the link for the new release: 
https://github.com/xie186/ViewBS/releases/tag/v0.1.7

Thanks.
Shaojun
