### ISSUE TITLE
ext_tools directory missing

### ISSUE THREAD

**Issue by MartinMcGrath** [xie186/ViewBS#29]
Hi,

Someone asked for [help](https://perlmonks.org/?node_id=1231286) installing this tool, I took a quick look and it seems as though the directory `ext_tools` is missing from the release  v0.1.7, while it is in the previous release. The `INSTALL.pl` looks for `cpanm` here, though the path is also referenced in a few other places

````
INSTALL.pl:my $CPANM = "$dir/ext_tools/cpanm";
lib/scripts/install.sh:chmod 755 ext_tools/cpanm
lib/scripts/install.sh:    ext_tools/cpanm Getopt::Long::Subcommand
lib/scripts/install.sh:    ext_tools/cpanm Bio::SeqIO
lib/scripts/install.sh:    ext_tools/cpanm Bio::DB::HTS::Tabix
README.md:    wget https://raw.githubusercontent.com/xie186/ViewBS/master/ext_tools/cpanm
````

**Comment by xie186** [comment]
Thanks for letting us know. Please `git clone https://github.com/xie186/ViewBS.git` to get the latest one. To make installation easier, we provide a wiki page to show you how to use conda to configure the environment: https://github.com/xie186/ViewBS#installation-via-conda-recommended

**Comment by MartinMcGrath** [comment]
Thanks for the very quick response, I've updated my post over at perlmonks.
