### ISSUE TITLE
Stuck with the top command

### ISSUE THREAD

**Issue by cherrypath** [xie186/ViewBS#3]
Can't locate SubCmd/MethGeno.pm in @INC (you may need to install the SubCmd::MethGeno module) (@INC contains: /Users/Yirong/bin/lib /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/Yirong/bin/ViewBS line 26.
BEGIN failed--compilation aborted at /Users/Yirong/bin/ViewBS line 26.

**Comment by readbio** [comment]
I guess you copied ViewBS to the bin directory: /Users/Yirong/bin/. If you do this, you also need to copy the lib directory into the bin directory.
Please the following piece of code. 
```
use lib dirname(abs_path $0) . '/lib';  #include self written packages in @INC.
```

**Comment by cherrypath** [comment]
THX!

Sent from my iPhone

On 18 Dec 2016, at 11:01 AM, readbio <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess you copied ViewBS to the bin directory. If you do this, you also need to copy the lib directory into the bin directory.

-
