### ISSUE TITLE
next

### ISSUE THREAD

**Issue by shenweima** [xie186/ViewBS#31]
In fact, an error was found using test data according to command of `ViewBS MethOneRegion --region chr2:2000-10000 --sample test_WT.tab.gz,test --prefix chr2:2000-10000 --context CHG`
```
Output prefix: chr2:2000-10000
Start calculate methylation information for target context
CHG
Can't call method "next" on an undefined value at /root/software/ViewBS/lib/Meth/OneRegion.pm line 60.
```
I have downloaded docker, but this error was also found

![image](https://user-images.githubusercontent.com/8536868/58363344-3ee77200-7ed5-11e9-9f03-40988768fb86.png)
I downloaded the test file again  and now it works well

**Comment by gourav924** [comment]
Did you figure out what was the reason for the error? I am stuck at it as well. I am using it on my machine

Thanks!

**Comment by yykaya** [comment]
Hi gourav94, 
This error is due to whether the total number of scaffolds in the reference genome is consistent or not. I recommend you to index and try the assembled genome in your project.
