### ISSUE TITLE
CpG methylation only

### ISSUE THREAD

**Issue by shawpa** [xie186/ViewBS#35]
Do any of these scripts work if you just have a file with CpG methylation only? In bismark I generally skip outputting Non-CpG methylation so my cytosine methylation report only has CpG sites. When I have tried a script like methGlobal, I didn't get any output in the .tab file for my sample or anything plotted in the PDF. I don't think it is an issue with the program installation because I downloaded the sample files and was able to run those and get the correct output. I don't get any error produced to troubleshoot when I run the command, I just don't get output.

**Comment by xie186** [comment]
Hi @shawpa , I'll test it out in the next two days and get back to you.
