### ISSUE TITLE
Problem with installing viewBS

### ISSUE THREAD

**Issue by hyl317** [xie186/ViewBS#37]
Hi, so I tried to install viewBS on Debian and got the following error. It seems like I am missing one package in my conda; so I checked  the /anaconda3/pkgs , and turns out I have libuuid-1.0.3-h1bed415_2  and libssh2-1.8.0-h5b517e9_2  but not the exact version as shown in the error message. I tried to install these package, yet I couldn't find that particular version. Any help?
```
yh362@mocha:~/tools/ViewBS-0.1.8$ conda env create --name env_ViewBS --file environment.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libssh2==1.8.0=h5b517e9_3
  - libuuid==1.0.3=1
```

```

**Comment by xie186** [comment]
Could you please try the file attached here? 
[environment.txt](https://github.com/xie186/ViewBS/files/3417395/environment.txt)
Please let me know if it works. Thanks. 
```
conda env create --name env_ViewBS --file environment.txt 
```

**Comment by hyl317** [comment]
If I use the new environment.txt, I got 

> yh362@mocha:~/tools/ViewBS-0.1.8$ conda env create --name env_ViewBS --file environment.txt

CondaValueError: invalid package specification: name: env_ViewBS

**Comment by xie186** [comment]
Please try this one
[environment.txt](https://github.com/xie186/ViewBS/files/3417668/environment.txt)

**Comment by hyl317** [comment]
emm.. I got the same error message.

**Comment by xie186** [comment]
Could you please show your conda version? 
```
conda -V
```

**Comment by hyl317** [comment]
> yh362@mocha:~$ conda --version
> conda 4.7.9
>

**Comment by hyl317** [comment]
Replacing libssh2==1.8.0=h5b517e9_3 with libssh2==1.8.0 and libuuid==1.0.3=1 with libuuid==1.0.3 in the 
original environment.yaml file seems to solve the problem. Thx!

**Comment by xie186** [comment]
Thanks. In the file provided here https://github.com/xie186/ViewBS/issues/37#issuecomment-513777556, I removed "build specification from dependencies" (eg. `=h5b517e9_3`). 
Instead of run:
```
wget https://github.com/xie186/ViewBS/files/3417395/environment.txt
conda env create --name env_ViewBS --file environment.txt 
```
we should run:
```
wget https://github.com/xie186/ViewBS/files/3417395/environment.txt
mv environment.txt environment.yaml
conda env create --name env_ViewBS --file environment.yaml
```

The suffix of the environment file matters here. But `.yaml` file is not allowed to be attached. 
If possible, please help me have a try.

**Comment by hyl317** [comment]
On my system, the environment is already there (CondaValueError: prefix already exists: /home/yh362/anaconda3/envs/env_ViewBS). But I can ask if someone else in my lab would like to have a try tomorrow. Thx for timely reply!

**Comment by aer-neo** [comment]
hello, I got the same error message.

conda env create --name env_ViewBS --file environment.yaml
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound: 
  - libuuid==1.0.3=1
  - libssh2==1.8.0=h5b517e9_3

I tried to run:

wget https://github.com/xie186/ViewBS/files/3417395/environment.txt
mv environment.txt environment.yaml
conda env create --name env_ViewBS --file environment.yaml

and, i got this:

conda env create --name env_ViewBS --file environment.yaml

Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - libssh2=1.8.0
  - r-pillar=1.3.1 -> r-base[version='>=3.6,<3.7.0a0'] -> libcurl[version='>=7.64.1,<8.0a0'] -> libssh2[version='>=1.8.2,<1.9.0a0']
Use "conda search <package> --info" to see the dependencies for each package.

**Comment by xie186** [comment]
I'm not sure why conda give the error message above. I think it's the problem of `conda`.  I'll try to collect more information to solve this problem. Currently I suggest you to either follow the instructions here (https://github.com/xie186/ViewBS#installation-of-dependencies-step-by-step) to install or generate the environment using the command lines below: 

```
conda create -n env_ViewBS
conda activate env_ViewBS
conda install -c anaconda perl
conda install -c bioconda perl-bio-db-hts 
conda install -c bioconda perl-bioperl 
conda install -c bioconda perl-app-cpanminus 
cpanm Getopt::Long::Subcommand
conda install -c r r-ggplot2 
conda install -c bioconda r-pheatmap 
conda install -c r r-reshape2 
conda install -c conda-forge r-cowplot 
```

Please let me know if you still have any other problems.

**Comment by avellab** [comment]
Hello,
I tried above script you mentioned, it didnt give me any error but when I used conda info --envs , the environment is not created.

wget https://github.com/xie186/ViewBS/files/3417395/environment.txt
mv environment.txt environment.yaml
conda env create --name env_ViewBS --file environment.yaml

**Comment by he-yunxiao** [comment]
Hello, I tried to install viewBS on Debian and got the following error，can you give me some adivice？When i ./ViewBS,it tell me 'Can't locate Bio/DB/HTS/Tabix.pm in @INC (you may need to install the Bio::DB::HTS::Tabix module)'. then i install the Bio::DB::HTS::Tabix module,it tell me ' Configure failed for Bio-DB-HTS-3.01. See /home/data/vip05/.cpanm/work/1608864197.2299507/build.log for details.'

**Comment by he-yunxiao** [comment]
details:
cpanm (App::cpanminus) 1.7044 on perl 5.026002 built for x86_64-linux-thread-multi
Work directory is /home/data/vip05/.cpanm/work/1608862721.2139162
You have make /usr/bin/make
You have LWP 6.39
You have /usr/bin/tar: tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Bio::DB::HTS::Tabix () on cpanmetadb ...
--> Working on Bio::DB::HTS::Tabix
Fetching http://www.cpan.org/authors/id/A/AV/AVULLO/Bio-DB-HTS-3.01.tar.gz
-> OK
Unpacking Bio-DB-HTS-3.01.tar.gz
Entering Bio-DB-HTS-3.01
Checking configure dependencies from META.json
Checking if you have ExtUtils::Install 1.46 ... Yes (2.06)
Checking if you have Module::Build 0.38 ... Yes (0.4231)
Configuring Bio-DB-HTS-3.01
Running Build.PL
Can't exec "/tmp/build/80754af9/perl_1527832170752/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc": No such file or directory at /home/data/vip05/anaconda3/envs/BS/lib/site_perl/5.26.2/ExtUtils/CBuilder/Base.pm line 342.
Warning: ExtUtils::CBuilder not installed or no compiler detected
Proceeding with configuration, but compilation may fail during Build


This module requires HTSlib (http://htslib.org/)
Install it if you have not done so already.

This script will attempt to locate HTSlib by looking for htslib/hts.h
and libhts.a / libhts.so in:

  1. --htslib command line argument
  2. HTSLIB_DIR environment variable
  3. --prefix command line argument (which also sets installation location)
  4. Alien::HTSlib dependency resolver
  5. pkg-config (extra directories can be set in PKG_CONFIG_PATH environment variable)
  6. common library locations: /usr /usr/local, /usr/share, /opt/local

-> N/A
-> FAIL Configure failed for Bio-DB-HTS-3.01. See /home/data/vip05/.cpanm/work/1608862721.2139162/build.log for details.

**Comment by he-yunxiao** [comment]
But what makes me sad is i have already installed ExtUtils::CBuilde.

**Comment by acontrerasg** [comment]
> I'm not sure why conda give the error message above. I think it's the problem of `conda`. I'll try to collect more information to solve this problem. Currently I suggest you to either follow the instructions here (https://github.com/xie186/ViewBS#installation-of-dependencies-step-by-step) to install or generate the environment using the command lines below:
> 
> ```
> conda create -n env_ViewBS
> conda activate env_ViewBS
> conda install -c anaconda perl
> conda install -c bioconda perl-bio-db-hts 
> conda install -c bioconda perl-bioperl 
> conda install -c bioconda perl-app-cpanminus 
> cpanm Getopt::Long::Subcommand
> conda install -c r r-ggplot2 
> conda install -c bioconda r-pheatmap 
> conda install -c r r-reshape2 
> conda install -c conda-forge r-cowplot 
> ```
> 
> Please let me know if you still have any other problems.
Hello there,
I just wanted to chime in  and say that this is the only way I managed to installed on Linux 4.19.140 x86_64.
Thanks!
