### ISSUE TITLE
Bug report: chromosome size beyond 2^29-1 (536870911)

### ISSUE THREAD

**Issue by xie186** [xie186/ViewBS#38]
If there is a chromosome bigger than 2^29-1 (536870911), you need to add `-C` when generating the index file:

```
## A file with suffix of `csi` will be generated
tabix -C -p vcf test.tab.gz
```

Warning messages will be added when there is any genomic coordinate beyond 2^29-1 (536870911).

**Comment by Brian1791** [comment]
Drs.Xie
      Thank you very much for your prompt answer. When I add the “-C” parameter, view-BS software work well. And I have another question was: which option can be used to  set the statistical interval when i use the "MethGeno" model ? The default interval is 500kb.

 Best regards.
 Jianxin Bian

**Comment by xie186** [comment]
Please see the information below: 
```
    --win [optional]
             - Window size. Default: 500000
    --step [optional]
             - Step size. Default: 500000
```

I'll include the help message in the next release. Currently it will be only shown in that latest master branch: https://github.com/xie186/ViewBS

**Comment by Brian1791** [comment]
Yes, thank you very much.
