### ISSUE TITLE
Division by zero error in MethOverRegion?

### ISSUE THREAD

**Issue by hyl317** [xie186/ViewBS#39]
When plotting MethOverRegion, I got the following error message when running MethOverRegion:

> Subcommand: MethOverRegion
> file:info.tab.txt
> The sample and region information is stored in file:info.tab.txt
> 
> It seemed that the reigons you provided are Genes. Please make sure of this.
> 
> Output directory is: /data/home/yh362/work/2019_Summer/epigenome/raw_reads/Root_samtools/MethOverRegion
> Output prefix: root
> A6528.root.combined.CX_report.txt.gz    Nsyl    Nsyl.v1.region
> A6528.root.combined.CX_report.txt.gz    Ntom    Ntom.v1.regionStart calculate methylation information for target context
> CG
> Use of uninitialized value $bin_length in division (/) at /data/home/yh362/tools/ViewBS-0.1.8/lib/Meth/OverRegion.pm line 128, <REGION> line 1.
> Illegal division by zero at /data/home/yh362/tools/ViewBS-0.1.8/lib/Meth/OverRegion.pm line 128, <REGION> line 1.

The command I have used:
> ~/tools/ViewBS-0.1.8/ViewBS MethOverRegion --sample file:info.tab.txt --prefix root --context CG --outdir MethOverRegion --flank 5000

However, if I don't specify --flank 5000 and just use the default values, it seems to work fine.

**Comment by aer-neo** [comment]
I have exactly the same problem.

**Comment by xie186** [comment]
I'll look into this issue this week. Thanks.

**Comment by spiya** [comment]
I am also getting the same error. Do you have any suggestion?

**Comment by aer-neo** [comment]
Hello, I ended up using another program in order to get the "Gene Density",
Batmeth2, I installed it by Anaconda3 and made it work, then I modified the
R files so that the output of these graphs were in PDF instead of PNG in
"BatMeth2/scripts/methylevel.elements.compare.r" and
"BatMeth2/scripts/methylevel.elements.r".

**Comment by xie186** [comment]
Sorry for the late response. I'll work on this tomorrow and let you know the results.

**Comment by asumann** [comment]
I have the same issue. Help needed! Thanks in advance.

**Comment by xiuru** [comment]
I have the same issue. Is there any suggestion?

**Comment by xie186** [comment]
Please download the code using `git clone https://github.com/xie186/ViewBS.git`. 

I'll work on other issues and release a new version. Sorry for taking such a long time to work on this.
