### ISSUE TITLE
Feature request: Remove Getopt::Long::Subcommand from dependencies?

### ISSUE THREAD

**Issue by bio15anu** [xie186/ViewBS#42]
I'm mainly suggesting this because it would be really nice to have a recipe for viewbs on bioconda. I just looked into it briefly to see if I could simply add one myself, but it seems like this perl library Getopt::Long::Subcommand is the bottleneck as it has many dependencies which are seemingly also not on conda.

How difficult would it be to replace this library with a very similar one which is on conda? Seems like Getopt::Long and Getopt::Long::Descriptive are there for example, or MooseX::App also seems to support this functionality. The alternative would be to see about adding all the individual Getopt::Long::Subcommand dependencies to conda I guess.

**Comment by xie186** [comment]
Thanks for the suggestion. We'll look into this and get back to you.

**Comment by yykaya** [comment]
Did you check the error? 

I still have the problem with this issue on conda although it seems properly installed with Perl libraries, I'm facing with:

> Can't locate Getopt/Long/Subcommand.pm in @INC (you may need to install the Getopt::Long::Subcommand module) 

Regardless of the subject, I do not see any open issues and although it is promising for your software that all issues are closed, you have answered most of the issues such as _**'I will look and back to you or we'll check xxx'**_ etc, but there is no solution!

Best
