### ISSUE TITLE
MethCoverage proportions off?

### ISSUE THREAD

**Issue by RRebo** [xie186/ViewBS#43]
Hi,
I ran ViewBS on two of my BS-seq samples and for MethCoverage I get : 

Sample | Context | Depth | Percentage
-- | -- | -- | --
NDPS122 | CG | 1 | 183.09557
NDPS122 | CG | 2 | 164.900895
NDPS122 | CG | 3 | 143.550174
NDPS122 | CG | 4 | 119.487774
NDPS122 | CG | 5 | 94.5660053
NDPS122 | CG | 6 | 70.9522451
NDPS110 | CG | 1 | 176.257886
NDPS110 | CG | 2 | 149.386972
NDPS110 | CG | 3 | 118.819988
NDPS110 | CG | 4 | 87.9548799
NDPS110 | CG | 5 | 60.4967229
NDPS110 | CG | 6 | 38.8154209

How do I have a percentage > 100? Sorry, this migt be stupid but I really don"t get it!
Thanks
R

**Comment by xie186** [comment]
Are you using the latest version? Thanks.

**Comment by RRebo** [comment]
Yes, Donwloaded last week. 0.1.8?

**Comment by xie186** [comment]
We'll look into this and get back to you ASAP.

**Comment by xie186** [comment]
I'm not able to reproduce a result like you showed. Could you please share me the data (or a subset) to reproduce the result you showed above. Thanks. You can send the data to me via email: xie186@purdue.edu.

**Comment by xie186** [comment]
Hi @RRebo,

Sorry for the late response. I checked your data. The problem was that the reference you used has large chunks of sequences with lower case bases. I have updated the code. Please use the latest version: https://github.com/xie186/ViewBS/releases

Best,
Shaojun
