### ISSUE TITLE
Problem with MethCoverage (Illegal division by zero)

### ISSUE THREAD

**Issue by weedcentipede** [xie186/ViewBS#46]
This could be related to #28 

So, I'm trying to follow the petit tutorial on the main page for Bismarck alignments (I've run the pipeline exactly the same as it's suggested) and with this command line ```/home/data/rrebollo/ViewBS-0.1.9/ViewBS MethCoverage --reference microvelia-longipes.fa --sample L1-M1-10-bmsnd.bismark.cov.gz,L1 --sample L2-M3-10-bmsnd.bismark.cov.gz,L2 --sample L3-M1-20-bmsnd.bismark.cov.gz,L3 --sample L4-M3-20-bmsnd.bismark.cov.gz,L4 --outdir methCoverage --prefix microvelia-longipes ```
I'm getting the following error: 
```
Subcommand: MethCoverage
Sample(s): L1-M1-10-bmsnd.bismark.cov.gz,L1 L2-M3-10-bmsnd.bismark.cov.gz,L2 L3-M1-20-bmsnd.bismark.cov.gz,L3 L4-M3-20-bmsnd.bismark.cov.gz,L4
Output directory is: /home/data/rrebollo/mlongipes/LuisAF/12-02-2020/methCoverage
Output prefix: microvelia-longipes
Start reading the methylation file
Even cytosine sites with 0 read covered was outputted so we are going to use the total row numbers for CG (CHG/CHH) as Denominator
Use of uninitialized value in multiplication (*) at /home/data/rrebollo/ViewBS-0.1.9/lib/Meth/Coverage.pm line 114.
Illegal division by zero at /home/data/rrebollo/ViewBS-0.1.9/lib/Meth/Coverage.pm line 114.
```
Is this caused by extremely low coverage, is there any recommendation for this error? 

Cheers, 
Luis Alfonso.

**Comment by xie186** [comment]
Hi Luis Alfonso,

Thanks for using ViewBS. Are you using the latest version? If so, would you be able to send me a piece of the file you are using? Thanks. My email is xie186@purdue.edu

Best,
Shaojun

**Comment by weedcentipede** [comment]
Hey Shaojun, 

I just sent it through we transfer the files I'm using, 

Cheers, 
Luis Alfonso.

**Comment by xie186** [comment]
I'll take  a look and get back to you (probably tomorrow). Thanks.

**Comment by xie186** [comment]
Sorry for the late response. Kids were sick. I didn't see the reference genome. You can either send it to me or tell me the link to download. Thanks.

**Comment by weedcentipede** [comment]
Hey, don't worry, kids first, I just shared the genome file through drive.

**Comment by weedcentipede** [comment]
Hey Shaojun, did you had time to check the data?
