### ISSUE TITLE
MethHeatmap and MethGeno Problems

### ISSUE THREAD

**Issue by hanahm1** [xie186/ViewBS#47]
Hi all,

I am having two issues that is probably associated with my not being familiar with ViewBS. 

First: MethGeno- I can successfully run MethGeno with CHH and CHG contexts. When I ask for CpG/CG context, the output graph puts all the samples at a methylation level of 1. I can't seem to figure out why. See code below:

`./ViewBS MethGeno --genomeLength /lab_data/hansen_lab/hanahm1/bosTau9_genome/bosTau9.fa.fai --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F272_C.bis_rep.cov.CX_report.txt.gz,C272 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F250_C.bis_rep.cov.CX_report.txt.gz,C250 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F268_C.bis_rep.cov.CX_report.txt.gz,C268 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F278_C.bis_rep.cov.CX_report.txt.gz,C278 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F307_PI.bis_rep.cov.CX_report.txt.gz,PI307 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F308_PI.bis_rep.cov.CX_report.txt.gz,PI308 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F842_PI.bis_rep.cov.CX_report.txt.gz,PI842 --maxChromNum 3000 --outdir /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/test_plots/ --prefix MethGeno --context CG
`
Second: MethHeatmap- I get the following error when running MethHeatmap

'Output directory is: /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/HeatMap
Output prefix: CHG-Hyper-HeatMap
Start calculate methylation information for target context
CHG
Error in read.table(cpg, header = T) : more columns than column names
Execution halted
Meth::Heatmap=HASH(0x55a968109380): Useage: R --vanilla --slave --input <> --height <heigtht> --width <width> --height2 <heigtht> --width2 <width> --random_region <random_region> --output1 <heat.pdf> --output2 <hist.pdf> < trans_DMS_heatmap.R 
/home/hanahm1/miniconda3/envs/ViewBS/lib/R/bin/exec/R --slave --no-restore --file=/home/hanahm1/ViewBS/ViewBS-0.1.9/lib/Meth/Heatmap.R --args --input /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/HeatMap/CHG-Hyper-HeatMap_MethHeatmap_CHG.txt --output1 /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/HeatMap/CHG-Hyper-HeatMap_MethHeatmap_CHG.pdf --output2 /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/HeatMap/CHG-Hyper-HeatMap_MethHist_CHG.pdf --cluster_cols FALSE --cluster_rows TRUE --height 10 --width 10 --height2 10 --width2 10 --random_region 2000 
FALSE TRUE 

Running time: 1 wallclock secs ( 0.44 usr  0.05 sys +  1.37 cusr  7.78 csys =  9.64 CPU)'

I'm certain it has to do with the reference table which can be seen below

'"chr13"	59054354	59054354	"NR_031115.1"
"chr16"	41909887	41909887	"XM_024976558.1"
"chr2"	131185958	131185958	"XM_015460007.2"
"chr25"	25228240	25228240	"XM_024985093.1"
"chr25"	27328872	27328872	"NM_001039957.1"
"chr25"	41206122	41206122	"NM_001206549.1"
"chr26"	23398931	23398931	"NM_174304.2"
"chr26"	39112822	39112822	"XM_024986064.1"
"chr27"	40512069	40512069	"XM_024986389.1"
"chr27"	40512073	40512073	"XM_024986389.1.a"
"chr27"	40512150	40512150	"XM_024986389.1.b"
'
I have tried with and without column headers. The code run is below:

'./ViewBS MethHeatmap --region /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/DMRs/CHG_hyper3.txt --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F272_C.bis_rep.cov.CX_report.txt.gz,C272 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F250_C.bis_rep.cov.CX_report.txt.gz,C250 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F268_C.bis_rep.cov.CX_report.txt.gz,C268 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F278_C.bis_rep.cov.CX_report.txt.gz,C278 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F307_PI.bis_rep.cov.CX_report.txt.gz,PI307 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F308_PI.bis_rep.cov.CX_report.txt.gz,PI308 --sample /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/Bismark_output/cytosine_reports/F842_PI.bis_rep.cov.CX_report.txt.gz,PI842 --outdir /lab_data/hansen_lab/hanahm1/Methyl-Seq/Methyl-Seq_Data/HeatMap/ --prefix CHG-Hyper-HeatMap --context CHG
'

Thank you so much for your help.

Best,

Hanah

**Comment by xie186** [comment]
Could you please attached a piece of the file with CG methylation information? You can send to my email at xie186@purdue.edu if you want to keep it confidential. Thanks.
