### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by moaine** [xie186/ViewBS#5]
Dear author,
I'm testing ViewBS with your example data but I did get an error message :

` ViewBS-master/ViewBS MethOverRegion --region genome/region.bed --sample bis_WT.tab.gz,WT --sample bis_cmt23.tab.gz,cmt23  --prefix test --context CHG
Subcommand: MethOverRegion
bis_WT.tab.gz,WT bis_cmt23.tab.gz,cmt23
genome/region.bed

It seemed that the reigons you provided are Genes. Please make sure of this.

Output directory is: /home/el/Downloads/ViewBS
Output prefix: test
Start calculate methylation information for target context
CHG

Warning message:
In min(tab$bin_num) : no non-missing arguments to min; returning Inf
Warning message:
In max(tab$bin_num) : no non-missing arguments to max; returning -Inf
Meth::OverRegion=HASH(0x2b37fa8): WARNING: unknown option '--input'

ARGUMENT '/home/el/Downloads/ViewBS/test_MethOverRegion_CHG.txt' __ignored__

WARNING: unknown option '--xlab'

ARGUMENT 'Gene' __ignored__

WARNING: unknown option '--height'

ARGUMENT '10' __ignored__

WARNING: unknown option '--width'

ARGUMENT '10' __ignored__

WARNING: unknown option '--adjustXaxis'

ARGUMENT '10' __ignored__

WARNING: unknown option '--output'

ARGUMENT '/home/el/Downloads/ViewBS/test_MethOverRegion_CHG.pdf' __ignored__

Usage: R --vanilla --slave --height <fig height> --width <fig width> --adjustXaxis <X> --input <input tab> --xlab <Gene>  --output <output> < OverRegion.R 
/usr/lib/R/bin/exec/R --vanilla --slave --input /home/el/Downloads/ViewBS/test_MethOverRegion_CHG.txt --xlab Gene --height 10 --width 10 --adjustXaxis 10 --output /home/el/Downloads/ViewBS/test_MethOverRegion_CHG.pdf 

Running time: 2 wallclock secs ( 0.05 usr  0.00 sys +  1.59 cusr  0.06 csys =  1.70 CPU)
`
Do you have an idea about the origin of this error ? 
Thanks in advance for your Help !

P.S : I'm runing ViewBS on Linux (ubuntu 16 LTS)

**Comment by readbio** [comment]
Can you try the data here: https://doi.org/10.6084/m9.figshare.4238990.v2
Sorry about the inconvenience.

**Comment by moaine** [comment]
Dear authors,
thank you for your quick reply I can not download all the file just the
index tabix for 3 files.

2017-02-08 17:29 GMT+01:00 readbio <notifications@github.com>:

**Comment by moaine** [comment]
I think the error message have something to do with R given the error
message that I got but I'm not sure at all. I did also re-index the
methylation file using tabix -p vcf but I still get the same error message

2017-02-08 18:47 GMT+01:00 Moaine Elbaidouri <moaine.elbaidouri@gmail.com>:

**Comment by moaine** [comment]
One more thing that maybe will help to understand the origin of the error is that the file test_MethOverRegion_CHG.txt is empty. So this may explain why R can not draw to plot.
Thanks again for your time

**Comment by readbio** [comment]
I'll work on this later.

**Comment by moaine** [comment]
Thank you for your time

**Comment by readbio** [comment]
Sorry for the late response. Please use the test data here:

https://gitlab.com/BS-seq/ViewBS_testdata

Can you try again? Thanks.

**Comment by readbio** [comment]
Please let me know if you have any other questions or suggestions. Thanks.

**Comment by moaine** [comment]
Many thanks that works ! you can close the issue now.


2017-02-21 2:51 GMT+01:00 readbio <notifications@github.com>:
