### ISSUE TITLE
ViewBS error No CXX

### ISSUE THREAD

**Issue by mw-qggp** [xie186/ViewBS#50]
Hi,
this is the end of my logfile after running ViewBS BisNonConvRate:

Start reading the methylation file
CXX

Error: CXX not existed in the input file. Please double check!
Running time:24578 wallclock secs (24252.07 usr 215.77 sys + 2879.78 cusr 268.14 csys = 27615.76 CPU)

The resulted BisNonConvRate-Table is empty. I used 14 samples. Can anybody help me? Thanks in advance

**Comment by Ma-hz** [comment]
Hi,
Have you solved this problem?
I also had the sample problem, but I don't know how to solve it.
