### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Carly-31** [xie186/ViewBS#52]
Running this code I got the error:
tabix  -C -p vcf
[E::hts_hopen] Failed to open file 
1F_clean_1_bismark_bt2_pe.bismark.cov.gz
[E::hts_open_format] Failed to open file "
1F_clean_1_bismark_bt2_pe.bismark.cov.gz" : Inappropriate file type or format
Couldn't open "F_clean_1_bismark_bt2_pe.bismark.cov.gz" : Inappropriate file type or format

**Comment by xie186** [comment]
Did you use `bgzip ` to generate the `*.gz` file?

**Comment by Carly-31** [comment]
Hello the issues was solved thank you.
