### ISSUE TITLE
ViewBS MethCoverage error

### ISSUE THREAD

**Issue by amit19bik** [xie186/ViewBS#55]
Hi,

i am runinng ViewBS MethCoverage and I am getting following error.

Use of uninitialized value in multiplication (*) at /ViewBS-0.1.6/lib/Meth/Coverage.pm line 103.
Illegal division by zero at /ViewBS-0.1.6/lib/Meth/Coverage.pm line 103.

i am running 

ViewBS MethCoverage --reference /genome --sample sample1_cov.CX_report.txt.gz,sample1 --sample sample2_cov.CX_report.txt.gz,sample2 --outdir coverage

Could you please let me know how to resolve this error.

Thank you.

**Comment by xie186** [comment]
Can you share me the files you used? My email is xie186@purdue.edu. Thanks.
