### ISSUE TITLE
Robustnesss suggestion for  OneRegion.R  script

### ISSUE THREAD

**Issue by acontrerasg** [xie186/ViewBS#56]
Hi there, 
Thanks for the package, I have been using it extensively. 
However, I have been experiencing an inconsistent behaviour in   the OneRegion.R file at line 20:
`ggsave(out, p, height=length(levels(tab[,1]))*par("din")[2]/6)`

I had to add a line to make sure  tab[,1]  is always interpreted as factor and not as character so length levels doesnt return 0.
like:
`   tab[,1] <- as.factor(tab[,1])`

Hope it helps,

Best
Adri

**Comment by xie186** [comment]
Thank you very much for the suggestion. I'll add it in the next release. 
Best,
Shaojun
