### ISSUE TITLE
Update README for ViewBS installation

### ISSUE THREAD

**Issue by xuzhougeng** [xie186/ViewBS#57]
I write a bioconda recipe for ViewBS, so now we can install ViewBS with one command

```bash
conda install -c bioconda viewbs
```

**Comment by xie186** [comment]
Fantastic! Thank you.

**Comment by xie186** [comment]
README.md updated! Thanks again.

**Comment by deltoroger** [comment]
Hello! is this working? I cannot install viewbs, I get "PackagesNotFoundError"
