### ISSUE TITLE
how to set the y axis scale for the profile in MethOverRegion

### ISSUE THREAD

**Issue by Liufan-YIN** [xie186/ViewBS#58]
Hello professor,
When I use the function MethOverRegion for DNA methylation profile on specific group of region, I find the profile in the pdf always is shown in the top. I don't find a parameter to adjust the y axis scale. The profile has been attached. I want to know how to set the y axis scale for the profile in MethOverRegion. 
<img width="458" alt="profile" src="https://user-images.githubusercontent.com/65107876/119154259-939e3300-ba84-11eb-86b2-9d9c051a9290.png">

**Comment by xie186** [comment]
Just in case you are still interested in this. 

After you run ViewBS, a shell script is also generated. You can make a new copy of the [R code] (https://github.com/xie186/ViewBS/blob/db51b1d4061d3d12444fa979d087ce7eff569c3e/lib/Meth/OverRegion.R).
You can insert the line below after [this](https://github.com/xie186/ViewBS/blob/db51b1d4061d3d12444fa979d087ce7eff569c3e/lib/Meth/OverRegion.R#L46):
```
p = p + ylim(min, max)
```
Then replace the new R script with the one used in the shell script. I'll try to add parameters to enable the adjustment of y-axis scale. Thanks for using ViewBS. My apologies for the late response.
