### ISSUE TITLE
The first base on the chromosome is 0 or 1 in your pipeline?

### ISSUE THREAD

**Issue by yu-z** [xie186/ViewBS#61]
Dear Shaojun,

For the MethHeatmap and MethOverRegion function, the pipeline need the start position and end position of certain region. The input files of MethHeatmap and MethOverRegion is a little different. Are they all bed files and the first base on the chromosome is 0?

Looking forward to your reply. 

Thanks,
Yu

**Comment by xie186** [comment]
Sorry for the late response. Just for future reference, the start position should be 1-based. I'll add this in the manual.
