### ISSUE TITLE
Unable to install using Conda

### ISSUE THREAD

**Issue by InfiniteLaugh** [xie186/ViewBS#62]
Hello!

  I just ran Conda to install ViewBS and apparently, there's some conflicts in the environment, listed below. My perl version is v5.26.2 and python version 2.7.5 (python 3 also not working). I try to install the correct version of environments but it seemed not to work well.  I was working on the research in DNA methylation and this software seems to meet my target.
  I will be delighted if you are willing to offer me some help!
  Best wishes & Happy Chinese new year !!!

`
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                                                                                     failed

UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (perl):

  - viewbs -> perl-bio-db-hts[version='>=3.0.1'] -> perl[version='>=5.32.1,<5.33.0a0',build=*_perl5]
  - viewbs -> perl[version='>=5.26.2,<5.26.3.0a0']

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package _libgcc_mutex conflicts for:
_libgcc_mutex
perl=5.26.2 -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge|main']
viewbs -> libgcc-ng[version='>=9.4.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge|main']
perl-app-cpanminus -> libgcc -> _libgcc_mutex=[build=free]
libgomp -> _libgcc_mutex==0.1[build='main|conda_forge']
_openmp_mutex -> _libgcc_mutex==0.1[build='main|conda_forge']

Package libgomp conflicts for:
libgomp
_openmp_mutex -> libgomp[version='>=7.5.0']

Package libgcc-ng conflicts for:
viewbs -> libgcc-ng[version='>=9.3.0|>=9.4.0']
perl-app-cpanminus -> perl[version='>=5.26.2,<5.27.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.5.0']
perl=5.26.2 -> libgcc-ng[version='>=7.2.0|>=7.5.0']
libgcc-ng
viewbs -> perl[version='>=5.26.2,<5.26.3.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.5.0|>=7.3.0']

Package _openmp_mutex conflicts for:
perl=5.26.2 -> libgcc-ng[version='>=7.5.0'] -> _openmp_mutex[version='>=4.5']
viewbs -> libgcc-ng[version='>=9.4.0'] -> _openmp_mutex[version='>=4.5']
_openmp_mutex

Package libstdcxx-ng conflicts for:
viewbs -> r-reshape2 -> libstdcxx-ng[version='7.2.0.*|>=7.2.0|>=7.3.0']
perl-app-cpanminus -> libgcc -> libstdcxx-ng[version='>=7.2.0']

Package perl conflicts for:
perl-app-cpanminus -> perl[version='5.22.0.*|>=5.26.2,<5.27.0a0']
perl-app-cpanminus -> perl-threaded -> perl
perl=5.26.2The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - perl=5.26.2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - viewbs -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

`

**Comment by xie186** [comment]
Could you please let me know your conda version and the command lines you ran starting from how you built the environment? Thanks.

**Comment by InfiniteLaugh** [comment]
> Could you please let me know your conda version and the command lines you ran starting from how you built the environment? Thanks.

Glad to receive your reply!

1. My conda version is 4.11.0
2. To verify the problem specifically, I, therefore, delete the previous environment that I modified many times and create a new one. The code is as follow:

`conda create -n viewbs`
`conda activate viewbs`
`conda install -c bioconda viewbs`


Then I received a shorter error:

`
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                                                                                     failed

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - viewbs -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

`

Under this environment, the perl version is 5.16.3, python version is 2.7.5 & 3.9.5.

Thanks again!

**Comment by xie186** [comment]
Sorry for the late response. Not sure why this happens. 
Here is an alternative way to use ViewBS:
1. install singularity on your server.
2. Run the command line below:
```
singularity -d build viewbs0.1.11.img docker://xie186/viewbs:0.1.11
```
You will get a file named `viewbs0.1.11.img`.
3. Then you can use ViewBS:

```
singularity exec viewbs0.1.11.img ViewBS --help
```
Hope this helps. I'll try my best to fix the conda issue. Thanks again.

**Comment by InfiniteLaugh** [comment]
> Sorry for the late response. Not sure why this happens. Here is an alternative way to use ViewBS:
> 
> 1. install singularity on your server.
> 2. Run the command line below:
> 
> ```
> singularity -d build viewbs0.1.11.img docker://xie186/viewbs:0.1.11
> ```
> 
> You will get a file named `viewbs0.1.11.img`. 3. Then you can use ViewBS:
> 
> ```
> singularity exec viewbs0.1.11.img ViewBS --help
> ```
> 
> Hope this helps. I'll try my best to fix the conda issue. Thanks again.

Thanks for your reply! 
Because I don't have the root authentication of the serve I use, therefore, I installed singularity in a newly built environment. Followed by this command:

`conda install -c conda-forge singularity`

Then I run the command line below:
`singularity -d build viewbs0.1.11.img docker://xie186/viewbs:0.1.11`

However, a fatal error was reported:

DEBUG   [U=1011,P=96132]   persistentPreRun()            Singularity version: 3.8.6
DEBUG   [U=1011,P=96132]   persistentPreRun()            Parsing configuration file /home/share_data1/zhoujx/software/miniconda3/envs/viewbs/etc/singularity/singularity.conf
DEBUG   [U=1011,P=96132]   handleConfDir()               Created /home/userdir/.singularity
DEBUG   [U=1011,P=96132]   getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=1011,P=96132]   initCacheDir()                Creating cache directory: /home/userdir/.singularity/cache
DEBUG   [U=1011,P=96132]   initCacheDir()                Creating cache directory: /home/share_data1/zhoujx/.singularity/cache/library
DEBUG   [U=1011,P=96132]   initCacheDir()                Creating cache directory: /home/share_data1/zhoujx/.singularity/cache/oci-tmp
DEBUG   [U=1011,P=96132]   initCacheDir()                Creating cache directory: /home/share_data1/zhoujx/.singularity/cache/shub
DEBUG   [U=1011,P=96132]   initCacheDir()                Creating cache directory: /home/share_data1/zhoujx/.singularity/cache/oras
DEBUG   [U=1011,P=96132]   initCacheDir()                Creating cache directory: /home/share_data1/zhoujx/.singularity/cache/net
DEBUG   [U=1011,P=96132]   newBundle()                   Created temporary directory "/tmp/bundle-temp-940900481" for the bundle
DEBUG   [U=1011,P=96132]   newBundle()                   Created directory "/tmp/build-temp-3607942860/rootfs" for the bundle
DEBUG   [U=1011,P=96132]   ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=1011,P=96132]   ensureGzipComp()              Gzip compression by default ensured
INFO    [U=1011,P=96132]   Full()                        Starting build...
DEBUG   [U=1011,P=96132]   Get()                         Reference: xie186/viewbs:0.1.11
Getting image source signatures
Copying blob 22dc81ace0ea done
Copying blob 1a8b3c87dba3 done
Copying blob 91390a1c435a done
Copying blob 07844b14977e done
Copying blob b78396653dae done
Copying blob 5fc7de8941e3 done
Copying blob 32d6067a414b done
Copying blob 0328d3decdfd done
Copying blob 34fc5adaec16 done
Copying blob 0bca11b3fe49 done
Copying blob 27c5ffeddba0 done
Copying blob 17893de31ac8 done
DEBUG   [U=1011,P=96132]   cleanUp()                     Cleaning up "/tmp/build-temp-3607942860/rootfs" and "/tmp/bundle-temp-940900481"
FATAL   [U=1011,P=96132]   runBuildLocal()               While performing build: conveyor failed to get: initializing source oci:/home/share_data1/zhoujx/.singularity/cache/blob:c16d971055a17849addfa109c1a7837c621ec62ea088d71f8c24926a7a350841: reading blob sha256:1489cd238f77120a58ea8770e02b2e7bbcf72092dab51d57369ee6797bd44830: unable to retrieve auth token: invalid username/password: errors:
unauthorized: authentication required
unauthorized: authentication required

My question is, can I install ViewBS through singularity WITHOUT root authentication, because I am operating on the public serve of our lab, I worry that install using root will affect other people's work.

Thanks again!

**Comment by InfiniteLaugh** [comment]
> Sorry for the late response. Not sure why this happens. Here is an alternative way to use ViewBS:
> 
> 1. install singularity on your server.
> 2. Run the command line below:
> 
> ```
> singularity -d build viewbs0.1.11.img docker://xie186/viewbs:0.1.11
> ```
> 
> You will get a file named `viewbs0.1.11.img`. 3. Then you can use ViewBS:
> 
> ```
> singularity exec viewbs0.1.11.img ViewBS --help
> ```
> 
> Hope this helps. I'll try my best to fix the conda issue. Thanks again.

Thanks for your answer! 

I installed singularity and proceed the first command, and successfully got a file `viewbs0.1.11.img`:
`singularity -d build viewbs0.1.11.img docker://xie186/viewbs:0.1.11`

However, the second command faced with FATAL error:
`singularity exec viewbs0.1.11.img ViewBS --help`

The error information was as below:

`INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting viewbs0.1.11.img: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled
: exit status 1`

I use root to run this command but get this instead:
`
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
/bin/bash: /usr/bin/lesspipe.sh: No such file or directory`

Wish to receive your reply!

**Comment by xie186** [comment]
Did you install `singularity` yourself? Or you just used the one already installed by the admins? 
Try to install it yourself using conda:
https://anaconda.org/conda-forge/singularity

What's the version of  `singularity`? Thanks.

**Comment by InfiniteLaugh** [comment]
> Did you install `singularity` yourself? Or you just used the one already installed by the admins? Try to install it yourself using conda: https://anaconda.org/conda-forge/singularity
> 
> What's the version of `singularity`? Thanks.

I installed `singularity` using conda, and its version is 3.8.6
Then I run the command
`chown softwares:softwares /opt/local/cluster-utils/conda/envs/singularity371`
followed by the instructing in this site: https://zhuanlan.zhihu.com/p/392073989

**Comment by xie186** [comment]
This is becuase of the configuration of singularity. Please see the info here: https://sylabs.io/guides/3.5/admin-guide/user_namespace.html

I noticed there were some updates of conda. Please try the command line again:
```
conda create -n viewbs -c bioconda viewbs
```

**Comment by InfiniteLaugh** [comment]
> This is becuase of the configuration of singularity. Please see the info here: https://sylabs.io/guides/3.5/admin-guide/user_namespace.html
> 
> I noticed there were some updates of conda. Please try the command line again:
> 
> ```
> conda create -n viewbs -c bioconda viewbs
> ```

Hello, Thanks for your answer.
I tried conda to install viewbs again, but unfortunately, still not working.
Therefore, I installed a virtual machine with centos on my PC and successfully installed the program with root. LOL
Thanks again for your patient answers!
