### ISSUE TITLE
MethOneRegion_PDF Page content might be truncated

### ISSUE THREAD

**Issue by StefaniaTuveri** [xie186/ViewBS#63]
Hello, 
I am having some problems with the function MethOneRegion.
All the files are correctly generated, but the .pdf file gives me an error once opening (Page content might be truncated).
The error file is empty, the output file states the following:

Subcommand: MethOneRegion
/.../GC1003962.merged.rmdup.cytosine_report.txt.gz,LuminalA /.../GC1003963.merged.rmdup.cytosine_report.txt.gz,Triple- /.../GC1003965.merged.rmdup.cytosine_report.txt.gz,Her2 /.../GC1003966.merged.rmdup.cytosine_report.txt.gz,LuminalB /.../GC1002313.merged.rmdup.cytosine_report.txt.gz,WBC1
chr17:39704100-39704550
Output directory is: /.../ViewBS-0.1.9/STK
Output prefix: onereg_chr17
Start calculate methylation information for target context
CG
Meth::OneRegion=HASH(0x2e377a8): Usage: R --vanilla --slave --input <input tab> --region <chr:stt-end> --output <output> < *R
/apps/leuven/skylake/2018a/software/R/4.0.2-foss-2018a-bare/lib64/R/bin/exec/R --no-echo --no-restore --file=/.../ViewBS-0.1.9/lib/Meth/OneRegion.R --args --input /.../ViewBS-0.1.9/STK/onereg_chr17_MethOneRegion_CG.txt --region 39704100-39704550 --output /.../ViewBS-0.1.9/STK/onereg_chr17_MethOneRegion_CG.pdf

Running time: 2 wallclock secs ( 0.21 usr  0.06 sys +  1.07 cusr  0.16 csys =  1.50 CPU)

**Comment by xie186** [comment]
Could you please check the content in `onereg_chr17_MethOneRegion_CG.txt` to see whether there is any information in the file? If possible, could you please send me a test data that I can reproduce your error. Thanks.

**Comment by StefaniaTuveri** [comment]
This is the content of the onereg_chr17_MethOneRegion_CG.txt :

Sample  chr     position        C_num   T_num   MethylationLevel
LuminalA        chr17   39704091        1       8       0.111111111111111
LuminalA        chr17   39704092        3       4       0.428571428571429
LuminalA        chr17   39704099        0       11      0
LuminalA        chr17   39704100        1       5       0.166666666666667
LuminalA        chr17   39704158        6       2       0.75
LuminalA        chr17   39704290        2       11      0.153846153846154
LuminalA        chr17   39704291        1       7       0.125
LuminalA        chr17   39704304        2       10      0.166666666666667
LuminalA        chr17   39704305        2       7       0.222222222222222
LuminalA        chr17   39704341        7       4       0.636363636363636
LuminalA        chr17   39704342        0       7       0
LuminalA        chr17   39704346        7       5       0.583333333333333
LuminalA        chr17   39704347        1       6       0.142857142857143
