### ISSUE TITLE
MethHeatmap

### ISSUE THREAD

**Issue by aditi-2017** [xie186/ViewBS#7]
Hello, 

ViewBS is working great for me except for option "MethHeatmap"

Could you please post the command line for MethHeatmap in the tutorial. Tutorial has a note as 
"Note: If the file has 4th column, each row in this column should be unique"
But in the test data file for heat map (CHG_hypo_DMR_drm12cmt23_to_WT.txt), the region input file is in text format with not a unique fourth column. I was able to run and create heat map using the test text file but it seems to be not working for my data. Can you please explain with an example what kind of input region file I can use with MethHeatmap option? 

Thank you !

**Comment by aditi-2017** [comment]
I get this error message :

Start calculate methylation information for target context
CHH
................................................................................................................................................................................................................................
 *** caught segfault ***
address 0x7f64366eaa08, cause 'memory not mapped'

Traceback:
 1: hclust(d, method = method)
 2: cluster_mat(mat, distance = clustering_distance_rows, method = clustering_method)
 3: pheatmap(x, show_rownames = F, cluster_rows = clus_row, cluster_cols = clus_col)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch({    pheatmap(x, show_rownames = F, cluster_rows = clus_row, cluster_cols = clus_col)}, error = function(err) {    x <- x[sample(1:nrow(x), RANDOM_NUM), ]    pheatmap(x, show_rownames = F, cluster_rows = clus_row, cluster_cols = clus_col)})
An irrecoverable exception occurred. R is aborting now ...
sh: line 1: 24882 Segmentation fault      R --vanilla --slave --input /omega/rambani/15feb17_cytosine_reports/VIEW_BS/HEATMAP/GENES_METHYLATION__MethHeatmap_CHH.txt --output1 /omega/rambani/15feb17_cytosine_reports/VIEW_BS/HEATMAP/GENES_METHYLATION__MethHeatmap_CHH.pdf --output2 /omega/rambani/15feb17_cytosine_reports/VIEW_BS/HEATMAP/GENES_METHYLATION__MethHist_CHH.pdf --cluster_cols FALSE --cluster_rows TRUE --height 10 --width 10 --height2 10 --width2 10 --random_region 2000 < /omega/rambani/software/ViewBS-master/lib/Meth/Heatmap.R
Meth::Heatmap=HASH(0x1ca4098): WARNING: unknown option '--input'

**Comment by readbio** [comment]
Got it. I'll let you know if I figure this out. Thanks.

**Comment by readbio** [comment]
Could you help me to check how many regions are there in the output file (data matrix)?
If possible, could you share me the file. Thanks.
