### ISSUE TITLE
Flank option in meth over region and meth one region

### ISSUE THREAD

**Issue by aditi-2017** [xie186/ViewBS#8]
Hello, 

Is it possible to set flanking region by option "-flank" as 0 or 10 for meth over region or meth one region command ? Right now if I try to set it as 10 I get this error : 

The flank region size should be able to divivied by 1000 with no remainder
The flank region size should be able to divivied by length of bin with no remainder

How can I change the length of flanking region in the output ? I will appreciate your reply. 

Thank you
Aditi

**Comment by readbio** [comment]
Currently, minimum length of '-length' should be 1000 bps and should be able to divided by 1000 with no remainder. 
My understanding is that you don't want the methylation patterns on the flanking region. Could you tell me a little bit more about your required feature? Then I can see whether I need to add this feature or not.

**Comment by aditi-2017** [comment]
Hello,

Thank you for your reply.

I want to show small single bp methylation differences in gene body exons
that might cause changes in RNA splicing, if I try to just plot one gene
body exon it adds 1000 bp upstream and downstream to it and the emphasis of
that single basepair difference is lost.

In other scenario, I only want to show differential methylation only in the
promoter region (emphasizing specific motifs), but with addition of
downstream flanking region some of the genic region is always included and
I will have to cut it out.

If there was an option to choose window for display in meth over one region
option and no flanking region unless specified, it would be nice. I am
still able to work around the current option, i was just wondering if the
other way was available.

Thank you

Aditi

**Comment by readbio** [comment]
I'll add the feature later. I'll let you know if I update the code. Thanks for your information.

**Comment by readbio** [comment]
I have update the codes. Now you can set the flanking region size for the subcommand MethOneRegion. Please let me know if you have further questions.

**Comment by aditi-2017** [comment]
That's great ! Thank you !

Aditi
